# Generated by Django 5.1.2 on 2024-11-27 15:48

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('justeatemail', models.CharField(blank=True, max_length=255, null=True)),
                ('justeatpw', models.CharField(blank=True, max_length=255, null=True)),
                ('mon_time_from', models.TimeField(default=datetime.time(0, 0))),
                ('mon_time_to', models.TimeField(default=datetime.time(23, 59))),
                ('tue_time_from', models.TimeField(default=datetime.time(0, 0))),
                ('tue_time_to', models.TimeField(default=datetime.time(23, 59))),
                ('wed_time_from', models.TimeField(default=datetime.time(0, 0))),
                ('wed_time_to', models.TimeField(default=datetime.time(23, 59))),
                ('thu_time_from', models.TimeField(default=datetime.time(0, 0))),
                ('thu_time_to', models.TimeField(default=datetime.time(23, 59))),
                ('fri_time_from', models.TimeField(default=datetime.time(0, 0))),
                ('fri_time_to', models.TimeField(default=datetime.time(23, 59))),
                ('sat_time_from', models.TimeField(default=datetime.time(0, 0))),
                ('sat_time_to', models.TimeField(default=datetime.time(23, 59))),
                ('sun_time_from', models.TimeField(default=datetime.time(0, 0))),
                ('sun_time_to', models.TimeField(default=datetime.time(23, 59))),
                ('mon_time_toggle', models.BooleanField(default=True)),
                ('tue_time_toggle', models.BooleanField(default=True)),
                ('wed_time_toggle', models.BooleanField(default=True)),
                ('thu_time_toggle', models.BooleanField(default=True)),
                ('fri_time_toggle', models.BooleanField(default=True)),
                ('sat_time_toggle', models.BooleanField(default=True)),
                ('sun_time_toggle', models.BooleanField(default=True)),
                ('email_notif', models.CharField(blank=True, max_length=255, null=True)),
                ('email_notif_toggle', models.BooleanField(default=True)),
                ('mobile_notif', models.CharField(blank=True, max_length=16, null=True)),
                ('mobile_notif_toggle', models.BooleanField(default=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('open_runs_toggle', models.BooleanField(default=True)),
                ('overflows_toggle', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_id', models.CharField(max_length=50)),
                ('zone_name', models.CharField(max_length=255)),
                ('zone_toggle', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
