# Generated by Django 5.1.2 on 2024-11-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
