# Generated by Django 5.1.2 on 2024-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thread_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
