# Generated by Django 5.1.2 on 2024-11-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stripe_plan_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
