# Generated by Django 5.1.2 on 2024-11-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_thread_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='bw_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pw_count',
            field=models.IntegerField(default=0),
        ),
    ]
