# Generated by Django 5.1.2 on 2024-11-22 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='id',
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
