# Generated by Django 5.1.2 on 2024-11-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
