"""
Django settings for justeat_bot project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from decimal import Decimal
from urllib.parse import urljoin

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-19a^l2jp7p&ic&u1i1c-=rs@7^@mq&76bxaxr^3x*yl_soo6#@'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://grabbereat.com',
    'https://backend.grabbereat.com'

]

CORS_ORIGIN_WHITELIST = [
    'http://grabbereat.com',
    'https://backend.grabbereat.com',
    'https://grabbereat.com',
    'http://127.0.0.1:3000',
]


CORS_ALLOWED_ORIGINS = [
    'http://grabbereat.com',
    'https://backend.grabbereat.com',
    'https://grabbereat.com',
    'http://127.0.0.1:3000',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",  # new
    'django.contrib.staticfiles',
    'bot',
    'justeat_bot',
    "pinax.referrals",
    "plans",
    "ordered_model",    
    'payments',  
    'plans_payments',
    'sequences',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # new
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    "pinax.referrals.middleware.SessionJumpingMiddleware",
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'justeat_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'justeat_bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'template1',
        'USER': 'postgres',
        'PASSWORD': 'admin@21@',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTH_USER_MODEL = 'bot.User'


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {  
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",  # new
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

PLANS_PLANS = {
    'basic': {
        'name': 'Basic Plan',
        'price': 10.00,
        'features': ['Feature 1', 'Feature 2'],
    },
    'premium': {
        'name': 'Premium Plan',
        'price': 30.00,
        'features': ['Feature 1', 'Feature 2', 'Feature 3'],
    },
}

PLANS_CURRENCY = 'GBP'

PLANS_PLAN_MODEL = 'plans.Plan'


PLANS_INVOICE_ISSUER = {
    "issuer_name": "My Company Ltd",
    "issuer_street": "48th Suny street",
    "issuer_zipcode": "111-456",
    "issuer_city": "Django City",
    "issuer_country": "PL",
    "issuer_tax_number": "PL123456789",
}

PLANS_TAX = Decimal("23.0")
PLANS_TAXATION_POLICY = "plans.taxation.eu.EUTaxationPolicy"
PLANS_TAX_COUNTRY = "PL"

MANAGE_PY_PATH = os.environ.get("MANAGE_PY_PATH", "./manage.py")

PLANS_CURRENCY = "GBP"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

LOGIN_REDIRECT_URL = "/"

ENABLE_FAKE_PAYMENTS = False

PAYMENT_MODEL = 'plans_payments.Payment'
PAYMENT_HOST = 'https://backend.grabbereat.com/'

# Settings for django-plans
PLANS_PAYMENT_BACKEND = 'payments.backend.stripe'  # or 'payments.backend.paypal' for PayPal

# Settings for django-payments (for Stripe example)
STRIPE_LIVE_PUBLIC_KEY = ''
STRIPE_LIVE_SECRET_KEY = ''

#STRIPE_LIVE_SECRET_KEY = ''
STRIPE_WEBHOOK_SECRET = ""
#STRIPE_WEBHOOK_SECRET = ''
#STRIPE_WEBHOOK_SECRET = ''
# django-payments settings
PAYMENT_VARIANTS = {
    'stripe': ('payments.stripe.StripeProviderV3', {
        'api_key': STRIPE_LIVE_SECRET_KEY,
    }),
}

PLANS_INVOICE_LOGO_URL = urljoin(STATIC_URL, 'logo.png')

PLANS_INVOICE_TEMPLATE = '/plans/invoices/PL_EN.html'

PLANS_ORDER_EXPIRATION = 7
PLANS_EXPIRATION_REMIND = [1, 3, 7]

CORS_ALLOW_ALL_ORIGINS = True

DJANGO_ALLOW_ASYNC_UNSAFE = True  # Only use this for development

ASGI_APPLICATION = 'justeat_bot.asgi.application'